# Site settings
title: "Save E. 12th St. for the People"
email: eastlakeunited@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Call and email your councilmembers now: we need to keep up public pressure on the City Council to ensure that the new request for proposals is a sincere effort to secure low income affordable housing on E. 12th St.
baseurl: "/savee12th/" # the subpath of your site, e.g. /blog/
url: "https://catachresis.github.io/"

# Build settings
markdown: kramdown
